/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SPRAY_H_RPCGEN
#define _SPRAY_H_RPCGEN

#include <rpc/rpc.h>

#define SPRAYMAX 8845

struct spraytimeval {
	u_int sec;
	u_int usec;
};
typedef struct spraytimeval spraytimeval;

struct spraycumul {
	u_int counter;
	spraytimeval clock;
};
typedef struct spraycumul spraycumul;

typedef struct {
	u_int sprayarr_len;
	char *sprayarr_val;
} sprayarr;

#define SPRAYPROG 100012
#define SPRAYVERS 1
#define SPRAYPROC_SPRAY 1
extern  void * sprayproc_spray_1();
#define SPRAYPROC_GET 2
extern  spraycumul * sprayproc_get_1();
#define SPRAYPROC_CLEAR 3
extern  void * sprayproc_clear_1();
extern int sprayprog_1_freeresult ();

/* the xdr functions */
extern bool_t xdr_spraytimeval ();
extern bool_t xdr_spraycumul ();
extern bool_t xdr_sprayarr ();

#endif /* !_SPRAY_H_RPCGEN */
