/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "key_prot.h"
/*
 * Sun RPC is a product of Sun Microsystems, Inc. and is provided for
 * unrestricted use provided that this legend is included on all tape
 * media and as a part of the software program in whole or part.  Users
 * may copy or modify Sun RPC without charge, but are not authorized
 * to license or distribute it to anyone else except as part of a product or
 * program developed by the user.
 *
 * SUN RPC IS PROVIDED AS IS WITH NO WARRANTIES OF ANY KIND INCLUDING THE
 * WARRANTIES OF DESIGN, MERCHANTIBILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE, OR ARISING FROM A COURSE OF DEALING, USAGE OR TRADE PRACTICE.
 *
 * Sun RPC is provided with no support and without any obligation on the
 * part of Sun Microsystems, Inc. to assist in its use, correction,
 * modification or enhancement.
 *
 * SUN MICROSYSTEMS, INC. SHALL HAVE NO LIABILITY WITH RESPECT TO THE
 * INFRINGEMENT OF COPYRIGHTS, TRADE SECRETS OR ANY PATENTS BY SUN RPC
 * OR ANY PART THEREOF.
 *
 * In no event will Sun Microsystems, Inc. be liable for any lost revenue
 * or profits or other special, indirect and consequential damages, even if
 * Sun has been advised of the possibility of such damages.
 *
 * Sun Microsystems, Inc.
 * 2550 Garcia Avenue
 * Mountain View, California  94043
 */
#if 0
#pragma ident	"@(#)key_prot.x	1.7	94/04/29 SMI"
#endif

/* Copyright (c)  1990, 1991 Sun Microsystems, Inc. */

/* 
 * Compiled from key_prot.x using rpcgen.
 * DO NOT EDIT THIS FILE!
 * This is NOT source code!
 */

bool_t
xdr_keystatus (xdrs, objp)
	XDR *xdrs;
	keystatus *objp;
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_keybuf (xdrs, objp)
	XDR *xdrs;
	keybuf objp;
{
	register int32_t *buf;

	 if (!xdr_opaque (xdrs, objp, HEXKEYBYTES))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_netnamestr (xdrs, objp)
	XDR *xdrs;
	netnamestr *objp;
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXNETNAMELEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cryptkeyarg (xdrs, objp)
	XDR *xdrs;
	cryptkeyarg *objp;
{
	register int32_t *buf;

	 if (!xdr_netnamestr (xdrs, &objp->remotename))
		 return FALSE;
	 if (!xdr_des_block (xdrs, &objp->deskey))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cryptkeyarg2 (xdrs, objp)
	XDR *xdrs;
	cryptkeyarg2 *objp;
{
	register int32_t *buf;

	 if (!xdr_netnamestr (xdrs, &objp->remotename))
		 return FALSE;
	 if (!xdr_netobj (xdrs, &objp->remotekey))
		 return FALSE;
	 if (!xdr_des_block (xdrs, &objp->deskey))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cryptkeyres (xdrs, objp)
	XDR *xdrs;
	cryptkeyres *objp;
{
	register int32_t *buf;

	 if (!xdr_keystatus (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case KEY_SUCCESS:
		 if (!xdr_des_block (xdrs, &objp->cryptkeyres_u.deskey))
			 return FALSE;
		break;
	}
	return TRUE;
}

bool_t
xdr_unixcred (xdrs, objp)
	XDR *xdrs;
	unixcred *objp;
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->uid))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->gid))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->gids.gids_val, (u_int *) &objp->gids.gids_len, MAXGIDS,
		sizeof (u_int), (xdrproc_t) xdr_u_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_getcredres (xdrs, objp)
	XDR *xdrs;
	getcredres *objp;
{
	register int32_t *buf;

	 if (!xdr_keystatus (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case KEY_SUCCESS:
		 if (!xdr_unixcred (xdrs, &objp->getcredres_u.cred))
			 return FALSE;
		break;
	}
	return TRUE;
}

bool_t
xdr_key_netstarg (xdrs, objp)
	XDR *xdrs;
	key_netstarg *objp;
{
	register int32_t *buf;

	 if (!xdr_keybuf (xdrs, objp->st_priv_key))
		 return FALSE;
	 if (!xdr_keybuf (xdrs, objp->st_pub_key))
		 return FALSE;
	 if (!xdr_netnamestr (xdrs, &objp->st_netname))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_key_netstres (xdrs, objp)
	XDR *xdrs;
	key_netstres *objp;
{
	register int32_t *buf;

	 if (!xdr_keystatus (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case KEY_SUCCESS:
		 if (!xdr_key_netstarg (xdrs, &objp->key_netstres_u.knet))
			 return FALSE;
		break;
	}
	return TRUE;
}
