# lib16020/Makefile -- MiNTLib.
# Copyright (C) 2000 Guido Flohr <gufl0000@stud.uni-sb.de>
#
# This file is part of the MiNTLib project, and may only be used
# modified and distributed under the terms of the MiNTLib project
# license, COPYMINT.  By continuing to use, modify, or distribute
# this file you indicate that you have read the license and
# understand and accept it fully.

SHELL = /bin/sh

srcdir = .
top_srcdir = ..
csrcdir = $(top_srcdir)/src
subdir = lib16020

libsize = 16020
instdir = m68020-60/mshort
cflags = -m68020-60 -m68881 -mshort

default: all

include $(top_srcdir)/buildrules
